apiVersion: v1alpha1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: loongcollector-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
